name: CI / Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lint (optional)
      run: |
        python -m pip install flake8
        flake8 --version || true

    - name: Run tests (none defined)
      run: echo "No tests defined"

    - name: Build Docker image (optional)
      run: |
        docker build -t dao-ledger:latest .
